version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_koneps
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - D:/workspace/docker/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis_koneps
    hostname: redis_koneps
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6389:6379"
    volumes:
      - D:/workspace/docker/redis_koneps/data:/data
    restart: always
volumes:
  db:
    driver: local